version: '2'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app/
    environment:
      RANCHER_URL:
      RANCHER_ACCESS_KEY:
      RANCHER_SECRET_KEY:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
